version: "3.9"

services:
  series-bot-postgresql:
    container_name: "series-bot-postgresql"
    image: postgres:16.1-alpine
    volumes:
      - series_bot_postgresql_data:/var/lib/postgresql/data
    env_file:
      - ./config/postgresql/.env.prod
    init: true

  series-bot-backend:
    container_name: "series-bot-backend"
    image: series-bot-backend:1.1
    build: ./backend/
    env_file:
      - ./config/postgresql/.env.prod
      - ./backend/config/.env.prod
    depends_on:
      - series-bot-postgresql
    volumes:
      - ./backend:/backend
    init: true

  series-bot-nginx:
    container_name: "series-bot-nginx"
    image: nginx:1.25.3-alpine
    ports:
      - 80:80
    volumes:
      - ./config/nginx/nginx.prod.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - series-bot-backend
    init: true

volumes:
  series_bot_postgresql_data: