version: "3.9"

services:
  postgresql:
    image: postgres:16.0-bookworm
    ports:
      - 5432:5432
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    env_file:
      - ./config/postgresql/.env.prod

  backend:
    build: ./backend/
    env_file:
      - ./config/postgresql/.env.prod
      - ./backend/config/.env.prod
    ports:
      - 8000:8000
    depends_on:
      - postgresql
    volumes:
      - ./backend:/backend
    command: >
      bash -c "poetry run alembic upgrade head
      && poetry run uvicorn --reload --host=0.0.0.0 --port=8000 app.main:app"

  nginx:
    image: nginx:1.25-bookworm
    ports:
      - 80:80
    volumes:
      - ./config/nginx/nginx.prod.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

volumes:
  postgresql_data: