"""added_cascade_to_series

Revision ID: 62d95ec567f8
Revises: 24c28125d3ab
Create Date: 2023-11-27 16:08:50.633338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62d95ec567f8'
down_revision: Union[str, None] = '24c28125d3ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('series_user_uuid_fkey', 'series', type_='foreignkey')
    op.create_foreign_key(None, 'series', 'user', ['user_uuid'], ['uuid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'series', type_='foreignkey')
    op.create_foreign_key('series_user_uuid_fkey', 'series', 'user', ['user_uuid'], ['uuid'])
    # ### end Alembic commands ###
